export interface ProductDetail {
  id: string;
  nombre: string;
  tagline: string;
  descripcion: string;
  caracteristicas: string[];
  beneficios: string[];
  imagenHero: string;
  galeriaFotos: string[];
  precioDesde?: number;
  garantia: string;
}

export const PRODUCT_DETAILS: Record<string, ProductDetail> = {
  BOX6100_ARES: {
    id: 'BOX6100_ARES',
    nombre: 'ARES',
    tagline: 'Toldo cofre motorizado de diseño elegante',
    descripcion: 'El toldo ARES es la solución premium para terrazas modernas. Cofre protector integrado, motorización Somfy, y materiales de primera calidad. Diseñado para máxima durabilidad y estética.',
    caracteristicas: [
      'Cofre protector de aluminio lacado',
      'Motorización Somfy RTS/iO opcional',
      'Tejido Sauleda 100% poliéster',
      '4 semanas de entrega',
      'Montaje sencillo sobre fachada o techo',
    ],
    beneficios: [
      'Protección total del tejido cuando está recogido',
      'Manejo motorizado con mando a distancia',
      'Colores RAL personalizables',
      'Silencioso y duradero',
      'Integración con domótica posible',
    ],
    imagenHero: '/box6100-ares-catalog.jpg',
    galeriaFotos: [
      '/box6100-ares-catalog.jpg',
      '/box6100-ares-1.jpg',
      '/box6100-ares-2.jpg',
    ],
    precioDesde: 1850,
    garantia: '10 años en estructura y motor',
  },
  BOX6000: {
    id: 'BOX6000',
    nombre: 'IRIS',
    tagline: 'Toldo cofre versátil para cualquier presupuesto',
    descripcion: 'El IRIS es el toldo cofre clásico de AWMA. Combinación perfecta de robustez, elegancia y precio accesible. Disponible en versión manual o motorizada.',
    caracteristicas: [
      'Cofre semicofre de aluminio',
      'Manual o motorizado',
      'Fácil instalación',
      'Amplia gama de colores',
      'Mantenimiento mínimo',
    ],
    beneficios: [
      'Larga duración bajo condiciones de playa',
      'Precio competitivo',
      'Soporte técnico directo de AWMA',
      'Repuestos disponibles',
      'Compatible con solaramas',
    ],
    imagenHero: '/box6000-iris-catalog.jpg',
    galeriaFotos: [
      '/box6000-iris-catalog.jpg',
      '/box6000-iris-1.jpg',
    ],
    precioDesde: 1400,
    garantia: '10 años',
  },
  BOX6100: {
    id: 'BOX6100',
    nombre: 'BOX6100',
    tagline: 'Cofre grande para proyectos comerciales',
    descripcion: 'Sistema profesional para espacios grandes. Robustez garantizada en entornos comerciales, hoteles y residencias. Motorización de serie.',
    caracteristicas: [
      'Cofre de gran capacidad',
      'Motor Somfy de potencia',
      'Refuerzo estructural',
      'Hasta 800 cm de línea',
      'Mantenimiento industrial',
    ],
    beneficios: [
      'Ideal para negocios',
      'Garantía extendida disponible',
      'Servicio técnico dedicado',
      'Accesorios avanzados',
      'Escalabilidad',
    ],
    imagenHero: '/box6100-catalog.jpg',
    galeriaFotos: [
      '/box6100-catalog.jpg',
    ],
    precioDesde: 2200,
    garantia: '10 años + opción extensión',
  },
  PL7000: {
    id: 'PL7000',
    nombre: 'Palillería 80×40',
    tagline: 'Pérgola de lamas fijas resistente',
    descripcion: 'Estructura de aluminio con palillería de madera tratada. Estética natural y moderna. Excelente resistencia al viento y durabilidad.',
    caracteristicas: [
      'Lamas de madera 80×40 mm',
      'Marco de aluminio anodizado',
      'Fácil instalación',
      'Sin motorización',
      'Mantenimiento bajo',
    ],
    beneficios: [
      'Aspecto natural y cálido',
      'Resistencia superior',
      'Bajo precio',
      'Sombra continua',
      'Compatible con plantas trepadoras',
    ],
    imagenHero: '/pl7000-catalog.jpg',
    galeriaFotos: [
      '/pl7000-catalog.jpg',
    ],
    precioDesde: 950,
    garantia: '5 años en estructura',
  },
  TX7900: {
    id: 'TX7900',
    nombre: 'TENXO',
    tagline: 'Pérgola motorizada con lamas orientables',
    descripcion: 'Lujo y funcionalidad. Pérgola moderna con lamas motorizadas orientables, tela enrollable y sistemas smart. Control total de la sombra y la ventilación.',
    caracteristicas: [
      'Lamas motorizadas y orientables',
      'Tela motorizada integrada',
      'Motor Somfy iO',
      'Diseño ultra moderno',
      'Control por aplicación móvil',
    ],
    beneficios: [
      'Máximo control de luz y ventilación',
      'Automatización inteligente',
      'Estética premium',
      'Resistencia a viento extremo',
      'Bajo mantenimiento',
    ],
    imagenHero: '/tenxo-catalog.png',
    galeriaFotos: [
      '/tenxo-catalog.png',
    ],
    precioDesde: 3200,
    garantia: '10 años en estructura, 5 en motor',
  },
  AV8400: {
    id: 'AV8400',
    nombre: 'NEXUS 80',
    tagline: 'Cortaviento vertical para terrazas',
    descripcion: 'Sistema vertical compacto. Protección contra viento lateral y privacidad. Cristal fijo, screen o tela enrollable.',
    caracteristicas: [
      'Cristal templado o screen',
      'Marco de aluminio anodizado',
      'Fácil desmontaje',
      'Instalación sin obras',
      'Opción tela motorizada',
    ],
    beneficios: [
      'Solución rápida y limpia',
      'Privacidad inmediata',
      'Luz natural preservada',
      'Precio accesible',
      'Ampliable',
    ],
    imagenHero: '/av8400-nexus80-catalog.jpg',
    galeriaFotos: [
      '/av8400-nexus80-catalog.jpg',
    ],
    precioDesde: 450,
    garantia: '5 años',
  },
  ART4100: {
    id: 'ART4100',
    nombre: 'ART 4100',
    tagline: 'Brazo articulado clásico retráctil',
    descripcion: 'El toldo de brazos retráctiles por excelencia. Fácil de instalar, máxima salida, y elegancia clásica. Manual o motorizado.',
    caracteristicas: [
      'Brazos retráctiles de aluminio',
      'Tejido Sauleda premium',
      'Manual o motorizado',
      'Hasta 500 cm de salida',
      'Instalación en fachada',
    ],
    beneficios: [
      'Clásico y funcional',
      'Bajo costo de instalación',
      'Máxima proyección horizontal',
      'Mantenimiento sencillo',
      'Gran variedad de colores',
    ],
    imagenHero: '/art4100-catalog.jpg',
    galeriaFotos: [
      '/art4100-catalog.jpg',
    ],
    precioDesde: 600,
    garantia: '10 años',
  },
  ART4110: {
    id: 'ART4110',
    nombre: 'ART 4110',
    tagline: 'Brazo articulado A1 Premium para grandes salidas',
    descripcion: 'Toldo de brazos articulados premium AWMA. Sistema A1 con tensión interna reforzada, ideal para terrazas amplias hasta 600 cm de línea. Manual o motorizado.',
    caracteristicas: [
      'Brazos A1 Premium con tensión interna',
      'Línea de 185 a 600 cm',
      'Salida de hasta 350 cm',
      'Tejido Sauleda premium',
      'Manual o motorizado Somfy',
    ],
    beneficios: [
      'Ideal para terrazas grandes',
      'Mayor robustez que el ART 4100',
      'Excelente relación calidad-precio',
      'Repuestos AWMA disponibles',
      'Instalación rápida en fachada',
    ],
    imagenHero: '/art4110-catalog.jpg',
    galeriaFotos: [
      '/art4110-catalog.jpg',
    ],
    precioDesde: 720,
    garantia: '10 años en estructura',
  },
  BOX5200: {
    id: 'BOX5200',
    nombre: 'SAMA',
    tagline: 'Toldo cofre compacto y elegante',
    descripcion: 'El SAMA es el cofre AWMA más accesible. Diseño compacto, líneas limpias y robustez probada. Perfecto para balcones y terrazas de tamaño medio.',
    caracteristicas: [
      'Cofre compacto de aluminio lacado',
      'Línea hasta 500 cm, salida hasta 250 cm',
      'Manual o motorizado Somfy',
      'Brazos SMART de tensión interna',
      'Soportes techo o entre paredes',
    ],
    beneficios: [
      'Solución económica de marca AWMA',
      'Protección total del tejido',
      'Tamaño contenido para balcones',
      'Fácil instalación',
      'Repuestos disponibles',
    ],
    imagenHero: '/box5200-sama-catalog.jpg',
    galeriaFotos: [
      '/box5200-sama-catalog.jpg',
    ],
    precioDesde: 990,
    garantia: '10 años',
  },
  BOX6010_INDIE: {
    id: 'BOX6010_INDIE',
    nombre: 'INDIE',
    tagline: 'Semicofre versátil y económico',
    descripcion: 'El INDIE es el semicofre IRIS-light: la barra frontal y el tejido quedan resguardados sin pagar un cofre completo. Ideal para clientes que buscan calidad AWMA al mejor precio.',
    caracteristicas: [
      'Semicofre de aluminio',
      'Línea hasta 500 cm, salida hasta 250 cm',
      'Manual o motorizado',
      'Brazos articulados SMART',
      'Compatible con sensores de viento y sol',
    ],
    beneficios: [
      'Mejor precio dentro de la gama IRIS',
      'Protege la barra frontal del agua',
      'Instalación sencilla',
      'Diseño discreto y moderno',
      'Repuestos AWMA garantizados',
    ],
    imagenHero: '/box6010-indie-catalog.jpg',
    galeriaFotos: [
      '/box6010-indie-catalog.jpg',
    ],
    precioDesde: 800,
    garantia: '10 años',
  },
  BOX6110: {
    id: 'BOX6110',
    nombre: 'CONCEPT',
    tagline: 'Cofre Concept con brazos reforzados',
    descripcion: 'El CONCEPT es el cofre AWMA pensado para grandes salidas. Brazos Concept con sistema de tensión interna y cofre robusto que aguanta línea hasta 600 cm.',
    caracteristicas: [
      'Cofre robusto de aluminio lacado',
      'Línea hasta 600 cm, salida hasta 400 cm',
      'Brazos Concept reforzados',
      'Motorización Somfy RTS o iO',
      'Regulación frontal de inclinación',
    ],
    beneficios: [
      'Diseñado para terrazas grandes',
      'Cofre cierra completamente el tejido',
      'Compatible con domótica',
      'Mayor durabilidad en exterior',
      'Acabados a medida',
    ],
    imagenHero: '/box6110-concept-catalog.jpg',
    galeriaFotos: [
      '/box6110-concept-catalog.jpg',
    ],
    precioDesde: 1220,
    garantia: '10 años',
  },
  BOX6300: {
    id: 'BOX6300',
    nombre: 'ALAND',
    tagline: 'Cofre cuadrado de líneas minimalistas',
    descripcion: 'El ALAND combina un cofre cuadrado de líneas rectas con cantos redondeados muy finos. Acabado premium, brazos Premium o Concept y rango de inclinación de hasta 75°.',
    caracteristicas: [
      'Cofre cuadrado con cantos redondeados',
      'Línea hasta 600 cm, salida hasta 400 cm',
      'Brazos Premium o Concept',
      'Inclinación de hasta 75°',
      'Iluminación LED opcional en cofre y brazos',
    ],
    beneficios: [
      'Diseño minimalista y elegante',
      'Sin necesidad de soporte central',
      'Iluminación LED integrable',
      'Brazos de gran resistencia',
      'Adaptable a fachadas modernas',
    ],
    imagenHero: '/box6300-aland-catalog.jpg',
    galeriaFotos: [
      '/box6300-aland-catalog.jpg',
    ],
    precioDesde: 1310,
    garantia: '10 años',
  },
  BOX6400: {
    id: 'BOX6400',
    nombre: 'LUSOL',
    tagline: 'Cofre premium con acabado curvo',
    descripcion: 'El LUSOL es el cofre AWMA de líneas curvas y acabado premium. Brazos reforzados, cofre estanco y motorización Somfy de serie en grandes medidas.',
    caracteristicas: [
      'Cofre estanco con perfil curvo',
      'Línea hasta 600 cm, salida hasta 400 cm',
      'Brazos Premium con tensión interna',
      'Motor Somfy RTS o iO',
      'Soportes techo, pared o entre paredes',
    ],
    beneficios: [
      'Estética suave y elegante',
      'Protección total del tejido',
      'Apto para terrazas amplias',
      'Compatible con sensores',
      'Repuestos AWMA',
    ],
    imagenHero: '/box6400-lusol-catalog.jpg',
    galeriaFotos: [
      '/box6400-lusol-catalog.jpg',
    ],
    precioDesde: 1430,
    garantia: '10 años',
  },
  BOX6500: {
    id: 'BOX6500',
    nombre: 'ARKO',
    tagline: 'Cofre robusto para grandes superficies',
    descripcion: 'El ARKO está pensado para terrazas grandes que necesitan un cofre reforzado. Brazos de alta capacidad, motorización Somfy de serie y acabado AWMA.',
    caracteristicas: [
      'Cofre reforzado de aluminio',
      'Línea hasta 600 cm, salida hasta 400 cm',
      'Brazos de alta capacidad',
      'Motorización Somfy de serie',
      'Refuerzo estructural premium',
    ],
    beneficios: [
      'Pensado para superficies amplias',
      'Resistencia al viento mejorada',
      'Cofre cierra herméticamente',
      'Compatible con sensores',
      'Servicio técnico AWMA',
    ],
    imagenHero: '/box6500-arko-catalog.jpg',
    galeriaFotos: [
      '/box6500-arko-catalog.jpg',
    ],
    precioDesde: 2425,
    garantia: '10 años',
  },
  BOX7000: {
    id: 'BOX7000',
    nombre: 'GEMINI',
    tagline: 'Cofre doble para salidas extra grandes',
    descripcion: 'El GEMINI es el cofre AWMA para proyectos exigentes: salida de hasta 600 cm gracias a su sistema doble. Ideal para terrazas profundas, hoteles y restauración.',
    caracteristicas: [
      'Cofre tipo doble (gemini)',
      'Línea hasta 600 cm, salida hasta 600 cm',
      'Brazos reforzados de gran capacidad',
      'Motorización Somfy de serie',
      'Estructura para uso profesional',
    ],
    beneficios: [
      'Salida única en su gama',
      'Pensado para hostelería',
      'Cobertura de terrazas profundas',
      'Calidad AWMA con garantía',
      'Servicio técnico dedicado',
    ],
    imagenHero: '/box7000-gemini-catalog.jpg',
    galeriaFotos: [
      '/box7000-gemini-catalog.jpg',
    ],
    precioDesde: 3830,
    garantia: '10 años',
  },
  BOX8100: {
    id: 'BOX8100',
    nombre: 'KYMA',
    tagline: 'Cofre vertical con tejido enrollable',
    descripcion: 'El KYMA es el toldo vertical con cofre AWMA. Tejido enrollable protegido por un cofre estanco, ideal para cerrar terrazas y porches con control solar.',
    caracteristicas: [
      'Cofre vertical estanco',
      'Línea hasta 360 cm, salida hasta 300 cm',
      'Tejido enrollable Sauleda',
      'Motorización Somfy de serie',
      'Apto para fachada y techo',
    ],
    beneficios: [
      'Protección solar vertical',
      'Cierre estanco del tejido',
      'Ideal como cortavientos',
      'Compatible con guías a cable o riel',
      'Estética limpia',
    ],
    imagenHero: '/box8100-kyma-catalog.jpg',
    galeriaFotos: [
      '/box8100-kyma-catalog.jpg',
    ],
    precioDesde: 2710,
    garantia: '10 años',
  },
  BOX8110: {
    id: 'BOX8110',
    nombre: 'KYMA VERTIKO',
    tagline: 'Vertical con cofre y guías verticales',
    descripcion: 'El KYMA VERTIKO es la evolución del KYMA con guías verticales rígidas. Mayor estabilidad frente al viento y cierre lateral perfecto para porches.',
    caracteristicas: [
      'Cofre estanco con guías verticales',
      'Línea hasta 360 cm, salida hasta 300 cm',
      'Tejido Sauleda enrollable',
      'Motorización Somfy de serie',
      'Cierre lateral hermético',
    ],
    beneficios: [
      'Mayor resistencia al viento',
      'Pensado para porches y terrazas',
      'Compatible con sistemas zip',
      'Estética premium',
      'Repuestos AWMA',
    ],
    imagenHero: '/box8110-kyma-vertiko-catalog.jpg',
    galeriaFotos: [
      '/box8110-kyma-vertiko-catalog.jpg',
    ],
    precioDesde: 3470,
    garantia: '10 años',
  },
  BOX8200: {
    id: 'BOX8200',
    nombre: 'KALI',
    tagline: 'Vertical premium con cofre y zip lateral',
    descripcion: 'El KALI es el vertical con cofre y guías zip de AWMA. Cierre hermético, estética premium y resistencia al viento. Solución profesional para cerrar porches.',
    caracteristicas: [
      'Cofre + guías zip laterales',
      'Línea hasta 367 cm, salida hasta 300 cm',
      'Tejido screen o Soltis',
      'Motorización Somfy de serie',
      'Cierre estanco total',
    ],
    beneficios: [
      'Cierre lateral hermético tipo zip',
      'Resistente a viento fuerte',
      'Ideal para hostelería',
      'Compatible con tejidos técnicos',
      'Estética minimalista',
    ],
    imagenHero: '/box8200-kali-catalog.jpg',
    galeriaFotos: [
      '/box8200-kali-catalog.jpg',
    ],
    precioDesde: 3220,
    garantia: '10 años',
  },
  BOX8300: {
    id: 'BOX8300',
    nombre: 'MAXIMUS',
    tagline: 'Vertical XXL para grandes cerramientos',
    descripcion: 'El MAXIMUS es el toldo vertical XXL de AWMA. Hasta 888 cm de línea para cubrir cerramientos enteros sin uniones. Pensado para hoteles, restaurantes y comunidades.',
    caracteristicas: [
      'Cofre XXL estanco',
      'Línea hasta 888 cm en una sola pieza',
      'Salida hasta 400 cm',
      'Tejido técnico Sauleda o Soltis',
      'Motorización Somfy de potencia',
    ],
    beneficios: [
      'Cubre grandes superficies sin uniones',
      'Pensado para profesionales',
      'Resistencia al viento mejorada',
      'Compatible con domótica',
      'Servicio técnico AWMA dedicado',
    ],
    imagenHero: '/box8300-maximus-catalog.jpg',
    galeriaFotos: [
      '/box8300-maximus-catalog.jpg',
    ],
    precioDesde: 5850,
    garantia: '10 años + extensión opcional',
  },
  PL7010: {
    id: 'PL7010',
    nombre: 'Palillería 80×40 D',
    tagline: 'Pérgola palillería 80×40 con desagüe integrado',
    descripcion: 'Versión "D" de la palillería 80×40: incorpora canalón de desagüe integrado en el larguero. Estética limpia y agua bien evacuada en zonas con lluvia.',
    caracteristicas: [
      'Lamas 80×40 mm de aluminio',
      'Larguero con desagüe integrado',
      'Línea hasta 700 cm, salida hasta 700 cm',
      'Sin motorización',
      'Mantenimiento bajo',
    ],
    beneficios: [
      'Mejor gestión del agua de lluvia',
      'Estética sin canalones visibles',
      'Aluminio sin mantenimiento',
      'Apto para zonas costeras',
      'Excelente relación calidad-precio',
    ],
    imagenHero: '/pl7010-catalog.jpg',
    galeriaFotos: [
      '/pl7010-catalog.jpg',
    ],
    precioDesde: 915,
    garantia: '5 años en estructura',
  },
  PL7020: {
    id: 'PL7020',
    nombre: 'Palillería 100×40',
    tagline: 'Pérgola palillería 100×40 con larguero',
    descripcion: 'Palillería con lamas 100×40 mm. Más rigidez y mayor cobertura por lama. Pensada para terrazas grandes donde se prima la robustez.',
    caracteristicas: [
      'Lamas 100×40 mm de aluminio',
      'Refuerzo con larguero perimetral',
      'Línea hasta 700 cm, salida hasta 700 cm',
      'Sin motorización',
      'Acabado anodizado o lacado',
    ],
    beneficios: [
      'Mayor rigidez estructural',
      'Cobertura más densa',
      'Resistente al viento',
      'Aluminio sin mantenimiento',
      'Apto para grandes superficies',
    ],
    imagenHero: '/pl7020-catalog.jpg',
    galeriaFotos: [
      '/pl7020-catalog.jpg',
    ],
    precioDesde: 1220,
    garantia: '5 años en estructura',
  },
  PL7030: {
    id: 'PL7030',
    nombre: 'Palillería 100×40 D',
    tagline: 'Pérgola palillería 100×40 autoportante con desagüe',
    descripcion: 'Versión autoportante de la 100×40 con desagüe integrado en larguero. Robustez, gestión del agua y autonomía estructural en una sola pérgola.',
    caracteristicas: [
      'Lamas 100×40 mm + larguero',
      'Estructura autoportante',
      'Desagüe integrado',
      'Línea hasta 700 cm, salida hasta 700 cm',
      'Acabado anodizado o lacado',
    ],
    beneficios: [
      'No necesita apoyarse en pared',
      'Desagüe oculto',
      'Resistencia al viento',
      'Estética premium',
      'Larga durabilidad en exterior',
    ],
    imagenHero: '/pl7030-catalog.jpg',
    galeriaFotos: [
      '/pl7030-catalog.jpg',
    ],
    precioDesde: 1420,
    garantia: '5 años en estructura',
  },
  AV8500: {
    id: 'AV8500',
    nombre: 'NEXUS 100',
    tagline: 'Vertical de cable hasta 325 cm de salida',
    descripcion: 'El NEXUS 100 es el cortaviento vertical estándar AWMA. Guías de cable, instalación sin obras y opción manual o motorizada.',
    caracteristicas: [
      'Guías de cable de acero',
      'Línea hasta 325 cm, salida hasta 300 cm',
      'Manual o motorizado',
      'Tejido screen o acrílico',
      'Marco aluminio anodizado',
    ],
    beneficios: [
      'Instalación rápida sin obras',
      'Solución asequible para terrazas',
      'Reduce viento y radiación lateral',
      'Compatible con tejidos técnicos',
      'Repuestos AWMA',
    ],
    imagenHero: '/av8500-nexus100-catalog.jpg',
    galeriaFotos: [
      '/av8500-nexus100-catalog.jpg',
    ],
    precioDesde: 925,
    garantia: '5 años',
  },
  AV8600: {
    id: 'AV8600',
    nombre: 'NEXUS 130',
    tagline: 'Vertical reforzado hasta 500 cm de línea',
    descripcion: 'El NEXUS 130 amplía las medidas del NEXUS con perfil reforzado. Pensado para terrazas grandes que necesitan un cortaviento vertical robusto.',
    caracteristicas: [
      'Perfil reforzado',
      'Línea hasta 500 cm, salida hasta 500 cm',
      'Guías de cable',
      'Manual o motorizado',
      'Tejido screen o acrílico',
    ],
    beneficios: [
      'Pensado para grandes medidas',
      'Cortavientos robusto',
      'Instalación sin obras',
      'Compatible con motorización',
      'Estética limpia',
    ],
    imagenHero: '/av8600-nexus130-catalog.jpg',
    galeriaFotos: [
      '/av8600-nexus130-catalog.jpg',
    ],
    precioDesde: 1130,
    garantia: '5 años',
  },
  AV8700: {
    id: 'AV8700',
    nombre: 'PARAVENTO',
    tagline: 'Cortaviento vertical compacto y económico',
    descripcion: 'El PARAVENTO es el cortaviento vertical más accesible de AWMA. Solución sencilla y eficaz para añadir privacidad y reducir viento en balcones.',
    caracteristicas: [
      'Cortaviento sin cofre',
      'Línea hasta 500 cm, salida hasta 325 cm',
      'Guías de cable',
      'Tejido screen o acrílico',
      'Manual de serie',
    ],
    beneficios: [
      'Solución muy económica',
      'Instalación rápida',
      'Aporta privacidad inmediata',
      'Mantenimiento mínimo',
      'Ideal para balcones',
    ],
    imagenHero: '/av8700-paravento-catalog.jpg',
    galeriaFotos: [
      '/av8700-paravento-catalog.jpg',
    ],
    precioDesde: 315,
    garantia: '5 años',
  },
  AV8750: {
    id: 'AV8750',
    nombre: 'PARABOX',
    tagline: 'Cortaviento vertical con cofre protector',
    descripcion: 'El PARABOX añade al PARAVENTO un cofre superior que protege el tejido cuando está recogido. Más durabilidad y mejor estética para terrazas a la intemperie.',
    caracteristicas: [
      'Cofre superior protector',
      'Línea hasta 500 cm, salida hasta 325 cm',
      'Guías de cable',
      'Manual o motorizado',
      'Tejido screen o acrílico',
    ],
    beneficios: [
      'Tejido protegido cuando se recoge',
      'Mayor durabilidad',
      'Estética limpia',
      'Apto para zonas costeras',
      'Repuestos AWMA',
    ],
    imagenHero: '/av8750-parabox-catalog.jpg',
    galeriaFotos: [
      '/av8750-parabox-catalog.jpg',
    ],
    precioDesde: 670,
    garantia: '5 años',
  },
  AV8770: {
    id: 'AV8770',
    nombre: 'IGLOOO',
    tagline: 'Toldo vertical técnico con cofre y guías',
    descripcion: 'El IGLOOO es el vertical técnico de AWMA. Cofre + guías rígidas para resistencia al viento y cierre lateral eficaz. Ideal para porches.',
    caracteristicas: [
      'Cofre + guías rígidas',
      'Línea hasta 400 cm, salida hasta 300 cm',
      'Motorización Somfy de serie',
      'Tejido screen, Soltis o acrílico',
      'Cierre lateral hermético',
    ],
    beneficios: [
      'Mayor resistencia al viento',
      'Pensado para porches cubiertos',
      'Cierre lateral hermético',
      'Tejido protegido por cofre',
      'Compatible con domótica',
    ],
    imagenHero: '/av8770-iglooo-catalog.jpg',
    galeriaFotos: [
      '/av8770-iglooo-catalog.jpg',
    ],
    precioDesde: 1230,
    garantia: '5 años',
  },
  'AV8870-1': {
    id: 'AV8870-1',
    nombre: 'NIMBUS',
    tagline: 'Vertical de cable sin cofre, grandes medidas',
    descripcion: 'El NIMBUS es el vertical de cable AWMA para grandes medidas. Solución sin cofre, instalación rápida y compatible con motorización Somfy.',
    caracteristicas: [
      'Vertical sin cofre',
      'Línea hasta 500 cm, salida hasta 325 cm',
      'Guías de cable',
      'Motorización Somfy opcional',
      'Tejido screen o acrílico',
    ],
    beneficios: [
      'Pensado para grandes medidas',
      'Instalación rápida y limpia',
      'Apto para terrazas y porches',
      'Bajo coste por m²',
      'Repuestos AWMA',
    ],
    imagenHero: '/av8870-nimbus-catalog.jpg',
    galeriaFotos: [
      '/av8870-nimbus-catalog.jpg',
    ],
    precioDesde: 670,
    garantia: '5 años',
  },
};

export function obtenerProductoDetail(id: string): ProductDetail | null {
  return PRODUCT_DETAILS[id] || null;
}
