export interface ProductDetail {
  id: string;
  nombre: string;
  tagline: string;
  descripcion: string;
  caracteristicas: string[];
  beneficios: string[];
  imagenHero: string;
  galeriaFotos: string[];
  precioDesde?: number;
  garantia: string;
  bajoConsulta?: boolean;
}

export const BAJO_CONSULTA_IDS = new Set([
  'BOX5200',
  'BOX6010_INDIE',
  'BOX6400',
  'BOX8110',
  'BOX8200',
]);

export const PRODUCT_DETAILS: Record<string, ProductDetail> = {
  BOX6100_ARES: {
    id: 'BOX6100_ARES',
    nombre: 'ARES',
    tagline: 'Toldo cofre motorizado de diseño elegante',
    descripcion: 'El toldo ARES es la solución premium para terrazas modernas. Cofre protector integrado, motorización Somfy, y materiales de primera calidad. Diseñado para máxima durabilidad y estética.',
    caracteristicas: [
      'Cofre protector de aluminio lacado',
      'Motorización Somfy RTS/iO opcional',
      'Tejido Sauleda 100% poliéster',
      '4 semanas de entrega',
      'Montaje sencillo sobre fachada o techo',
    ],
    beneficios: [
      'Protección total del tejido cuando está recogido',
      'Manejo motorizado con mando a distancia',
      'Colores RAL personalizables',
      'Silencioso y duradero',
      'Integración con domótica posible',
    ],
    imagenHero: '/box6100-ares-catalog.jpg',
    galeriaFotos: [
      '/box6100-ares-catalog.jpg',
      '/box6100-ares-1.jpg',
      '/box6100-ares-2.jpg',
    ],
    precioDesde: 1850,
    garantia: '10 años en estructura y motor',
  },
  BOX6000: {
    id: 'BOX6000',
    nombre: 'IRIS',
    tagline: 'Toldo cofre versátil para cualquier presupuesto',
    descripcion: 'El IRIS es el toldo cofre clásico de AWMA. Combinación perfecta de robustez, elegancia y precio accesible. Disponible en versión manual o motorizada.',
    caracteristicas: [
      'Cofre semicofre de aluminio',
      'Manual o motorizado',
      'Fácil instalación',
      'Amplia gama de colores',
      'Mantenimiento mínimo',
    ],
    beneficios: [
      'Larga duración bajo condiciones de playa',
      'Precio competitivo',
      'Soporte técnico directo de AWMA',
      'Repuestos disponibles',
      'Compatible con solaramas',
    ],
    imagenHero: '/box6000-iris-catalog.jpg',
    galeriaFotos: [
      '/box6000-iris-catalog.jpg',
      '/box6000-iris-1.jpg',
    ],
    precioDesde: 1400,
    garantia: '10 años',
  },
  BOX6100: {
    id: 'BOX6100',
    nombre: 'BOX6100',
    tagline: 'Cofre grande para proyectos comerciales',
    descripcion: 'Sistema profesional para espacios grandes. Robustez garantizada en entornos comerciales, hoteles y residencias. Motorización de serie.',
    caracteristicas: [
      'Cofre de gran capacidad',
      'Motor Somfy de potencia',
      'Refuerzo estructural',
      'Hasta 800 cm de línea',
      'Mantenimiento industrial',
    ],
    beneficios: [
      'Ideal para negocios',
      'Garantía extendida disponible',
      'Servicio técnico dedicado',
      'Accesorios avanzados',
      'Escalabilidad',
    ],
    imagenHero: '/box6100-catalog.jpg',
    galeriaFotos: [
      '/box6100-catalog.jpg',
    ],
    precioDesde: 2200,
    garantia: '10 años + opción extensión',
  },
  PL7000: {
    id: 'PL7000',
    nombre: 'Palillería 80×40',
    tagline: 'Pérgola de lamas fijas resistente',
    descripcion: 'Estructura de aluminio con palillería de madera tratada. Estética natural y moderna. Excelente resistencia al viento y durabilidad.',
    caracteristicas: [
      'Lamas de madera 80×40 mm',
      'Marco de aluminio anodizado',
      'Fácil instalación',
      'Sin motorización',
      'Mantenimiento bajo',
    ],
    beneficios: [
      'Aspecto natural y cálido',
      'Resistencia superior',
      'Bajo precio',
      'Sombra continua',
      'Compatible con plantas trepadoras',
    ],
    imagenHero: '/pl7000-catalog.jpg',
    galeriaFotos: [
      '/pl7000-catalog.jpg',
    ],
    precioDesde: 950,
    garantia: '5 años en estructura',
  },
  TX7900: {
    id: 'TX7900',
    nombre: 'TENXO',
    tagline: 'Pérgola motorizada con lamas orientables',
    descripcion: 'Lujo y funcionalidad. Pérgola moderna con lamas motorizadas orientables, tela enrollable y sistemas smart. Control total de la sombra y la ventilación.',
    caracteristicas: [
      'Lamas motorizadas y orientables',
      'Tela motorizada integrada',
      'Motor Somfy iO',
      'Diseño ultra moderno',
      'Control por aplicación móvil',
    ],
    beneficios: [
      'Máximo control de luz y ventilación',
      'Automatización inteligente',
      'Estética premium',
      'Resistencia a viento extremo',
      'Bajo mantenimiento',
    ],
    imagenHero: '/tenxo-catalog.png',
    galeriaFotos: [
      '/tenxo-catalog.png',
    ],
    precioDesde: 3200,
    garantia: '10 años en estructura, 5 en motor',
  },
  AV8400: {
    id: 'AV8400',
    nombre: 'NEXUS 80',
    tagline: 'Cortaviento vertical para terrazas',
    descripcion: 'Sistema vertical compacto. Protección contra viento lateral y privacidad. Cristal fijo, screen o tela enrollable.',
    caracteristicas: [
      'Cristal templado o screen',
      'Marco de aluminio anodizado',
      'Fácil desmontaje',
      'Instalación sin obras',
      'Opción tela motorizada',
    ],
    beneficios: [
      'Solución rápida y limpia',
      'Privacidad inmediata',
      'Luz natural preservada',
      'Precio accesible',
      'Ampliable',
    ],
    imagenHero: '/av8400-nexus80-catalog.jpg',
    galeriaFotos: [
      '/av8400-nexus80-catalog.jpg',
    ],
    precioDesde: 450,
    garantia: '5 años',
  },
  ART4100: {
    id: 'ART4100',
    nombre: 'ART 4100',
    tagline: 'Brazo articulado clásico retráctil',
    descripcion: 'El toldo de brazos retráctiles por excelencia. Fácil de instalar, máxima salida, y elegancia clásica. Manual o motorizado.',
    caracteristicas: [
      'Brazos retráctiles de aluminio',
      'Tejido Sauleda premium',
      'Manual o motorizado',
      'Hasta 500 cm de salida',
      'Instalación en fachada',
    ],
    beneficios: [
      'Clásico y funcional',
      'Bajo costo de instalación',
      'Máxima proyección horizontal',
      'Mantenimiento sencillo',
      'Gran variedad de colores',
    ],
    imagenHero: '/art4100-catalog.jpg',
    galeriaFotos: [
      '/art4100-catalog.jpg',
    ],
    precioDesde: 600,
    garantia: '10 años',
  },
  ART4110: {
    id: 'ART4110',
    nombre: 'ART 4110 A1 Premium',
    tagline: 'Toldo grande de brazo extensible estándar Premium',
    descripcion: 'Toldo grande de brazo extensible estándar Premium. Sistema A1 con tensión interna reforzada, ideal para terrazas amplias hasta 600 cm de línea. Manual o motorizado.',
    caracteristicas: [
      'Brazos A1 Premium con tensión interna',
      'Línea de 185 a 600 cm',
      'Salida de hasta 350 cm',
      'Tejido Sauleda premium',
      'Manual o motorizado Somfy',
    ],
    beneficios: [
      'Ideal para terrazas grandes',
      'Mayor robustez que el ART 4100',
      'Excelente relación calidad-precio',
      'Repuestos AWMA disponibles',
      'Instalación rápida en fachada',
    ],
    imagenHero: '/art4110-catalog.jpg',
    galeriaFotos: [
      '/art4110-catalog.jpg',
    ],
    precioDesde: 720,
    garantia: '10 años en estructura',
  },
  BOX5200: {
    id: 'BOX5200',
    nombre: 'SAMA',
    tagline: 'Toldo cofre compacto y elegante',
    descripcion: 'El SAMA es el cofre AWMA más accesible. Diseño compacto, líneas limpias y robustez probada. Perfecto para balcones y terrazas de tamaño medio.',
    caracteristicas: [
      'Cofre compacto de aluminio lacado',
      'Línea hasta 500 cm, salida hasta 250 cm',
      'Manual o motorizado Somfy',
      'Brazos SMART de tensión interna',
      'Soportes techo o entre paredes',
    ],
    beneficios: [
      'Solución económica de marca AWMA',
      'Protección total del tejido',
      'Tamaño contenido para balcones',
      'Fácil instalación',
      'Repuestos disponibles',
    ],
    imagenHero: '/box5200-sama-catalog.jpg',
    galeriaFotos: [
      '/box5200-sama-catalog.jpg',
    ],
    garantia: '10 años',
    bajoConsulta: true,
  },
  BOX6010_INDIE: {
    id: 'BOX6010_INDIE',
    nombre: 'INDIE',
    tagline: 'Semicofre versátil y económico',
    descripcion: 'El INDIE es el semicofre IRIS-light: la barra frontal y el tejido quedan resguardados sin pagar un cofre completo. Ideal para clientes que buscan calidad AWMA al mejor precio.',
    caracteristicas: [
      'Semicofre de aluminio',
      'Línea hasta 500 cm, salida hasta 250 cm',
      'Manual o motorizado',
      'Brazos articulados SMART',
      'Compatible con sensores de viento y sol',
    ],
    beneficios: [
      'Mejor precio dentro de la gama IRIS',
      'Protege la barra frontal del agua',
      'Instalación sencilla',
      'Diseño discreto y moderno',
      'Repuestos AWMA garantizados',
    ],
    imagenHero: '/box6010-indie-catalog.jpg',
    galeriaFotos: [
      '/box6010-indie-catalog.jpg',
    ],
    garantia: '10 años',
    bajoConsulta: true,
  },
  BOX6110: {
    id: 'BOX6110',
    nombre: 'CONCEPT',
    tagline: 'Cofre redondo con brazo articulado CONCEPT',
    descripcion: 'Toldo cofre redondo con brazo articulado CONCEPT y soportes estándar a pared. Pensado para grandes salidas (hasta 400 cm) con tensión interna y cofre robusto.',
    caracteristicas: [
      'Cofre robusto de aluminio lacado',
      'Línea hasta 600 cm, salida hasta 400 cm',
      'Brazos Concept reforzados',
      'Motorización Somfy RTS o iO',
      'Regulación frontal de inclinación',
    ],
    beneficios: [
      'Diseñado para terrazas grandes',
      'Cofre cierra completamente el tejido',
      'Compatible con domótica',
      'Mayor durabilidad en exterior',
      'Acabados a medida',
    ],
    imagenHero: '/box6110-concept-catalog.jpg',
    galeriaFotos: [
      '/box6110-concept-catalog.jpg',
    ],
    precioDesde: 1220,
    garantia: '10 años',
  },
  BOX6300: {
    id: 'BOX6300',
    nombre: 'ALAND',
    tagline: 'Cofre cuadrado de líneas minimalistas',
    descripcion: 'Toldo cofre cuadrado Aland New con brazo articulado PREMIUM y soportes estándar a pared o techo. Acabado premium con cantos redondeados y rango de inclinación de hasta 75°.',
    caracteristicas: [
      'Cofre cuadrado con cantos redondeados',
      'Línea hasta 600 cm, salida hasta 400 cm',
      'Brazos Premium o Concept',
      'Inclinación de hasta 75°',
      'Iluminación LED opcional en cofre y brazos',
    ],
    beneficios: [
      'Diseño minimalista y elegante',
      'Sin necesidad de soporte central',
      'Iluminación LED integrable',
      'Brazos de gran resistencia',
      'Adaptable a fachadas modernas',
    ],
    imagenHero: '/box6300-aland-catalog.jpg',
    galeriaFotos: [
      '/box6300-aland-catalog.jpg',
    ],
    precioDesde: 1310,
    garantia: '10 años',
  },
  BOX6400: {
    id: 'BOX6400',
    nombre: 'LUSOL',
    tagline: 'Cofre premium con acabado curvo',
    descripcion: 'El LUSOL es el cofre AWMA de líneas curvas y acabado premium. Brazos reforzados, cofre estanco y motorización Somfy de serie en grandes medidas.',
    caracteristicas: [
      'Cofre estanco con perfil curvo',
      'Línea hasta 600 cm, salida hasta 400 cm',
      'Brazos Premium con tensión interna',
      'Motor Somfy RTS o iO',
      'Soportes techo, pared o entre paredes',
    ],
    beneficios: [
      'Estética suave y elegante',
      'Protección total del tejido',
      'Apto para terrazas amplias',
      'Compatible con sensores',
      'Repuestos AWMA',
    ],
    imagenHero: '/box6400-lusol-catalog.jpg',
    galeriaFotos: [
      '/box6400-lusol-catalog.jpg',
    ],
    garantia: '10 años',
    bajoConsulta: true,
  },
  BOX6500: {
    id: 'BOX6500',
    nombre: 'ARKO',
    tagline: 'Cofre redondo con brazo Arko y tira LED opcional',
    descripcion: 'Toldo cofre redondo con brazo articulado Arko y soportes estándar a pared o techo. Cofre apto para tira de led integrada. Regulación frontal de inclinación.',
    caracteristicas: [
      'Cofre redondo de aluminio lacado',
      'Línea hasta 600 cm, salida hasta 400 cm',
      'Brazo articulado Arko',
      'Cofre apto para tira de LED',
      'Regulación frontal de inclinación',
    ],
    beneficios: [
      'Iluminación LED integrable en cofre',
      'Pensado para superficies amplias',
      'Cofre cierra herméticamente',
      'Inclinación ajustable desde frontal',
      'Servicio técnico AWMA',
    ],
    imagenHero: '/box6500-arko-catalog.jpg',
    galeriaFotos: [
      '/box6500-arko-catalog.jpg',
    ],
    precioDesde: 2425,
    garantia: '10 años',
  },
  BOX7000: {
    id: 'BOX7000',
    nombre: 'GEMINI',
    tagline: 'Semicofre autoportante a dos aguas',
    descripcion: 'Toldo semicofre autoportante a dos aguas con un mismo eje de 80×40 y brazo Premium. Sujeción a suelo mediante pie atornillado. Pensado para cubrir terrazas exentas o islas centrales.',
    caracteristicas: [
      'Semicofre autoportante a dos aguas',
      'Eje compartido 80×40 mm',
      'Brazos Premium',
      'Sujeción al suelo con pie atornillado',
      'Salida hasta 600 cm por cada lado',
    ],
    beneficios: [
      'No necesita pared ni techo de apoyo',
      'Cubre el doble de superficie',
      'Estructura única en su gama',
      'Pensado para hostelería e islas',
      'Servicio técnico AWMA',
    ],
    imagenHero: '/box7000-gemini-catalog.jpg',
    galeriaFotos: [
      '/box7000-gemini-catalog.jpg',
    ],
    precioDesde: 3830,
    garantia: '10 años',
  },
  BOX8100: {
    id: 'BOX8100',
    nombre: 'KYMA',
    tagline: 'Cofre redondo con brazo Premium y perfil cubre lonas',
    descripcion: 'Toldo cofre redondo con brazo articulado Premium. Soportes estándar a pared. Perfil de caída estándar Kyma y perfil cubre lonas para protección extra del tejido.',
    caracteristicas: [
      'Cofre redondo de aluminio',
      'Brazo articulado Premium',
      'Línea hasta 360 cm, salida hasta 300 cm',
      'Perfil de caída estándar Kyma',
      'Perfil cubre lonas integrado',
    ],
    beneficios: [
      'Tejido doblemente protegido',
      'Estética compacta',
      'Brazo Premium con tensión interna',
      'Soportes estándar a pared',
      'Repuestos AWMA disponibles',
    ],
    imagenHero: '/box8100-kyma-catalog.jpg',
    galeriaFotos: [
      '/box8100-kyma-catalog.jpg',
    ],
    precioDesde: 2710,
    garantia: '10 años',
  },
  BOX8110: {
    id: 'BOX8110',
    nombre: 'KYMA VERTIKO',
    tagline: 'Vertical con cofre y guías verticales',
    descripcion: 'El KYMA VERTIKO es la evolución del KYMA con guías verticales rígidas. Mayor estabilidad frente al viento y cierre lateral perfecto para porches.',
    caracteristicas: [
      'Cofre estanco con guías verticales',
      'Línea hasta 360 cm, salida hasta 300 cm',
      'Tejido Sauleda enrollable',
      'Motorización Somfy de serie',
      'Cierre lateral hermético',
    ],
    beneficios: [
      'Mayor resistencia al viento',
      'Pensado para porches y terrazas',
      'Compatible con sistemas zip',
      'Estética premium',
      'Repuestos AWMA',
    ],
    imagenHero: '/box8110-kyma-vertiko-catalog.jpg',
    galeriaFotos: [
      '/box8110-kyma-vertiko-catalog.jpg',
    ],
    garantia: '10 años',
    bajoConsulta: true,
  },
  BOX8200: {
    id: 'BOX8200',
    nombre: 'KALI',
    tagline: 'Vertical premium con cofre y zip lateral',
    descripcion: 'El KALI es el vertical con cofre y guías zip de AWMA. Cierre hermético, estética premium y resistencia al viento. Solución profesional para cerrar porches.',
    caracteristicas: [
      'Cofre + guías zip laterales',
      'Línea hasta 367 cm, salida hasta 300 cm',
      'Tejido screen o Soltis',
      'Motorización Somfy de serie',
      'Cierre estanco total',
    ],
    beneficios: [
      'Cierre lateral hermético tipo zip',
      'Resistente a viento fuerte',
      'Ideal para hostelería',
      'Compatible con tejidos técnicos',
      'Estética minimalista',
    ],
    imagenHero: '/box8200-kali-catalog.jpg',
    galeriaFotos: [
      '/box8200-kali-catalog.jpg',
    ],
    garantia: '10 años',
    bajoConsulta: true,
  },
  BOX8300: {
    id: 'BOX8300',
    nombre: 'MAXIMUS',
    tagline: 'Toldo cofre XXL con brazo Maximus',
    descripcion: 'Toldo cofre con brazo articulado Maximus y soportes estándar a pared. Hasta 888 cm de línea para cubrir cerramientos enteros sin uniones. Pensado para hoteles, restaurantes y comunidades.',
    caracteristicas: [
      'Cofre XXL de aluminio',
      'Brazo articulado Maximus de alta capacidad',
      'Línea hasta 888 cm en una sola pieza',
      'Salida hasta 400 cm',
      'Soportes estándar a pared',
    ],
    beneficios: [
      'Cubre grandes superficies sin uniones',
      'Pensado para uso profesional',
      'Brazo Maximus reforzado',
      'Compatible con motorización Somfy',
      'Servicio técnico AWMA dedicado',
    ],
    imagenHero: '/box8300-maximus-catalog.jpg',
    galeriaFotos: [
      '/box8300-maximus-catalog.jpg',
    ],
    precioDesde: 5850,
    garantia: '10 años + extensión opcional',
  },
  PL7010: {
    id: 'PL7010',
    nombre: 'Palillería 80×40 Pared Portería',
    tagline: 'Pérgola pared-portería con palillo simple 80×40',
    descripcion: 'Palillería pared-portería con palillo simple y guía 80×40. Estructura clásica con un extremo apoyado en pared y el otro en pies (portería). Sombra continua, sin motorización.',
    caracteristicas: [
      'Lamas/palillo simple 80×40 mm',
      'Configuración pared-portería',
      'Línea hasta 700 cm, salida hasta 700 cm',
      'Sin motorización',
      'Acabado anodizado o lacado',
    ],
    beneficios: [
      'Estructura clásica y robusta',
      'Aluminio sin mantenimiento',
      'Apto para zonas costeras',
      'Sombra continua densa',
      'Excelente relación calidad-precio',
    ],
    imagenHero: '/pl7010-catalog.jpg',
    galeriaFotos: [
      '/pl7010-catalog.jpg',
    ],
    precioDesde: 915,
    garantia: '5 años en estructura',
  },
  PL7020: {
    id: 'PL7020',
    nombre: 'Palillería 80×40 Pared Portería + Larguero',
    tagline: 'Pared-portería 80×40 con refuerzo lateral',
    descripcion: 'Palillería pared-portería 80×40 con palillo simple y perfil de refuerzo lateral (larguero). Mayor rigidez y resistencia al viento para vanos más amplios.',
    caracteristicas: [
      'Estructura 80×40 mm',
      'Palillo simple',
      'Perfil refuerzo lateral (larguero)',
      'Línea hasta 700 cm, salida hasta 700 cm',
      'Acabado anodizado o lacado',
    ],
    beneficios: [
      'Mayor rigidez estructural',
      'Resistente al viento',
      'Aluminio sin mantenimiento',
      'Apto para grandes superficies',
      'Larga durabilidad en exterior',
    ],
    imagenHero: '/pl7020-catalog.jpg',
    galeriaFotos: [
      '/pl7020-catalog.jpg',
    ],
    precioDesde: 1220,
    garantia: '5 años en estructura',
  },
  PL7030: {
    id: 'PL7030',
    nombre: 'Palillería 80×40 Autoportante + Larguero',
    tagline: 'Pérgola autoportante 80×40 con palillo simple',
    descripcion: 'Palillería autoportante con estructura 80×40 y palillo simple. No necesita apoyarse en pared: cuatro pies con larguero perimetral.',
    caracteristicas: [
      'Estructura 80×40 mm autoportante',
      'Palillo simple',
      'Larguero perimetral',
      'Línea hasta 700 cm, salida hasta 700 cm',
      'Acabado anodizado o lacado',
    ],
    beneficios: [
      'No necesita pared ni techo de apoyo',
      'Versátil para cualquier emplazamiento',
      'Resistencia al viento',
      'Aluminio sin mantenimiento',
      'Apto para zonas costeras',
    ],
    imagenHero: '/pl7030-catalog.jpg',
    galeriaFotos: [
      '/pl7030-catalog.jpg',
    ],
    precioDesde: 1420,
    garantia: '5 años en estructura',
  },
  AV8500: {
    id: 'AV8500',
    nombre: 'NEXUS 100 Cable',
    tagline: 'Toldo cofre vertical Nexus 100 mm con cable',
    descripcion: 'Toldo cofre vertical Nexus 100 mm con cable. Guías de cable de acero, instalación sin obras y opción manual o motorizada.',
    caracteristicas: [
      'Guías de cable de acero',
      'Línea hasta 325 cm, salida hasta 300 cm',
      'Manual o motorizado',
      'Tejido screen o acrílico',
      'Marco aluminio anodizado',
    ],
    beneficios: [
      'Instalación rápida sin obras',
      'Solución asequible para terrazas',
      'Reduce viento y radiación lateral',
      'Compatible con tejidos técnicos',
      'Repuestos AWMA',
    ],
    imagenHero: '/av8500-nexus100-catalog.jpg',
    galeriaFotos: [
      '/av8500-nexus100-catalog.jpg',
    ],
    precioDesde: 925,
    garantia: '5 años',
  },
  AV8600: {
    id: 'AV8600',
    nombre: 'NEXUS 130 Cable',
    tagline: 'Toldo cofre vertical Nexus 130 mm con cable',
    descripcion: 'Toldo cofre vertical Nexus 130 mm con cable. Perfil reforzado para grandes medidas (hasta 500 cm de línea y salida).',
    caracteristicas: [
      'Perfil reforzado',
      'Línea hasta 500 cm, salida hasta 500 cm',
      'Guías de cable',
      'Manual o motorizado',
      'Tejido screen o acrílico',
    ],
    beneficios: [
      'Pensado para grandes medidas',
      'Cortavientos robusto',
      'Instalación sin obras',
      'Compatible con motorización',
      'Estética limpia',
    ],
    imagenHero: '/av8600-nexus130-catalog.jpg',
    galeriaFotos: [
      '/av8600-nexus130-catalog.jpg',
    ],
    precioDesde: 1130,
    garantia: '5 años',
  },
  AV8700: {
    id: 'AV8700',
    nombre: 'PARAVENTO',
    tagline: 'Vertical cortavientos con puente abatible inoxidable',
    descripcion: 'Toldo vertical cortavientos. Perfil de caída con sistema de anilla y puente abatible inoxidable. Solución sencilla y eficaz para añadir privacidad y reducir viento.',
    caracteristicas: [
      'Cortavientos sin cofre',
      'Línea hasta 500 cm, salida hasta 325 cm',
      'Perfil de caída con anilla',
      'Puente abatible de acero inoxidable',
      'Manual o motorizado',
    ],
    beneficios: [
      'Solución muy económica',
      'Instalación rápida',
      'Aporta privacidad inmediata',
      'Mantenimiento mínimo',
      'Ideal para balcones',
    ],
    imagenHero: '/av8700-paravento-catalog.jpg',
    galeriaFotos: [
      '/av8700-paravento-catalog.jpg',
    ],
    precioDesde: 315,
    garantia: '5 años',
  },
  AV8750: {
    id: 'AV8750',
    nombre: 'PARABOX',
    tagline: 'Cofre vertical cortavientos con guías y pestillo',
    descripcion: 'Toldo cofre vertical cortavientos con guías y perfil de caída con sistema de pestillo. Cofre superior que protege el tejido cuando está recogido.',
    caracteristicas: [
      'Cofre superior protector',
      'Guías rígidas con perfil',
      'Perfil de caída con sistema de pestillo',
      'Línea hasta 500 cm, salida hasta 325 cm',
      'Manual o motorizado',
    ],
    beneficios: [
      'Tejido protegido cuando se recoge',
      'Mayor durabilidad',
      'Estética limpia',
      'Apto para zonas costeras',
      'Repuestos AWMA',
    ],
    imagenHero: '/av8750-parabox-catalog.jpg',
    galeriaFotos: [
      '/av8750-parabox-catalog.jpg',
    ],
    precioDesde: 670,
    garantia: '5 años',
  },
  AV8770: {
    id: 'AV8770',
    nombre: 'IGLOO',
    tagline: 'Vertical cofre cuadrado con guías de varilla',
    descripcion: 'Toldo vertical cofre cuadrado (Igloo). Perfil de caída con sistema de cerrojillo. Guías rígidas con perfil de varilla.',
    caracteristicas: [
      'Cofre cuadrado vertical',
      'Guías rígidas con perfil de varilla',
      'Perfil de caída con cerrojillo',
      'Línea hasta 400 cm, salida hasta 300 cm',
      'Motorización Somfy disponible',
    ],
    beneficios: [
      'Mayor resistencia al viento',
      'Pensado para porches cubiertos',
      'Cierre lateral hermético',
      'Tejido protegido por cofre',
      'Compatible con domótica',
    ],
    imagenHero: '/av8770-iglooo-catalog.jpg',
    galeriaFotos: [
      '/av8770-iglooo-catalog.jpg',
    ],
    precioDesde: 1230,
    garantia: '5 años',
  },
  'AV8870-1': {
    id: 'AV8870-1',
    nombre: 'NIMBUS sin Cofre',
    tagline: 'Vertical Screen Nimbus con cable inox o varilla',
    descripcion: 'Toldo vertical Screen Nimbus con cable inox o varilla. Sin cofre. Solución limpia y económica para grandes medidas.',
    caracteristicas: [
      'Vertical Screen sin cofre',
      'Guías de cable inox o varilla',
      'Línea hasta 500 cm, salida hasta 325 cm',
      'Tejido Screen técnico',
      'Manual o motorizado',
    ],
    beneficios: [
      'Pensado para grandes medidas',
      'Instalación rápida y limpia',
      'Apto para terrazas y porches',
      'Bajo coste por m²',
      'Repuestos AWMA',
    ],
    imagenHero: '/av8870-nimbus-catalog.jpg',
    galeriaFotos: [
      '/av8870-nimbus-catalog.jpg',
    ],
    precioDesde: 670,
    garantia: '5 años',
  },
};

export function obtenerProductoDetail(id: string): ProductDetail | null {
  return PRODUCT_DETAILS[id] || null;
}
